runtime: nodejs18
service: aarya-backend
env: standard
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 10
env_variables:
  SUPABASE_URL: "https://nrguygvgryfugpllkbjy.supabase.co"
  SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yZ3V5Z3ZncnlmdWdwbGxrYmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MTE3NDEsImV4cCI6MjA1Njk4Nzc0MX0.fNMoD5m8xF7I0YH9GUktuHN1qNpl-CWC1DTSFn8qgFQ" 